Emoji tabs
MariaChumerina/emoji-widget pull request #13
Opened 2020-11-28 22:08 UTC by Ludmilishee

https://github.com/MariaChumerina/emoji-widget/issues/5

2020-12-01 15:45 UTC, MariaChumerina requested changes

2020-12-01 15:45 UTC, MariaChumerina commented on src/widget.js
> +import categoriesData from './data/categories';
а может лучше не импортировать их здесь, а принимать в конструкторе класса? тогда виджет будет более универсальным

2020-12-01 15:45 UTC, MariaChumerina commented on src/widget.js
> +        this.showPageByCategory(1);
тут не совсем понятно, что это за единица)

2020-12-01 15:52 UTC, MariaChumerina commented on src/widget.js
> +        this.showPageByCategory(1);
я про то, что немного как магическое число выглядит, хотя точно не знаю, может и норм

2020-12-01 16:19 UTC, Ludmilishee commented on src/widget.js
> +import categoriesData from './data/categories';
тогда он в будущей задаче не нарисует сам себя при передаче input element. Точнее придётся ему передавать ещё и данные при инициализации. Ну то есть по смыслу компонент не будет самостоятельным. Предлагаю сделать передачу кастомных данных в конфигурации в конструкторе, но по умолчанию оставить "свои" данные, чтобы он не терялся при их отсуствии

2020-12-02 07:03 UTC, MariaChumerina approved these changes

2020-12-02 07:03 UTC, merged